192.168.2.11:
  hostname: 192.168.2.11
  password: George1347$
  platform: cisco_ios
  port: 22
  username: garciag1646
192.168.2.12:
  hostname: 192.168.2.12
  password: George1347$
  platform: cisco_ios
  port: 22
  username: garciag1646
